name: 'Manual Scraper Test'

on:
  workflow_dispatch:
  schedule:
    - cron: '40 8 30 10 *'

jobs:
  run-test-scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # === THÊM BƯỚC NÀY VÀO ===
      - name: Get Chrome Version
        id: chrome_version # Đặt ID cho bước này
        run: |
          # Lấy chuỗi phiên bản (vd: "Google Chrome 140.0.7339.0")
          VERSION_STRING=$(google-chrome --version)
          # Trích xuất số phiên bản chính (vd: "140")
          VERSION_MAIN=$(echo $VERSION_STRING | cut -d " " -f 3 | cut -d "." -f 1)
          # Lưu nó vào biến môi trường của GHA
          echo "CHROME_VERSION=$VERSION_MAIN" >> $GITHUB_ENV
          echo "Detected Chrome version: $VERSION_MAIN"
      # === KẾT THÚC THÊM BƯỚC ===

      - name: Run Udemy Scraper TEST
        env:
          HEADLESS: "true"
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          # Truyền phiên bản đã phát hiện vào script Python
          INSTALLED_CHROME_VERSION: ${{ env.CHROME_VERSION }}
        run: |
          python udemy_scraper.py \
            --job-type "test_run" \
            --category-name "Software Testing" \
            --category-url "https://www.udemy.com/courses/development/software-testing/" \
            --start-page 1 \
            --end-page 5 # Sửa lại 5 trang như trong log của bạn
      
      - name: Upload Debug Artifacts
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: artifacts/
